### ISSUE TITLE
Parsing multiple sexprs?

### ISSUE THREAD

**Issue by atg** [anko/sexpr-plus#2]
I may just be an idiot, but how does one parse multiple sexprs in the same input?

```
parse("(foo) (bar)")
```

throws a parse exception `SyntaxError: Expected comment, end of input or whitespace but "(" found.`

...OK so I looked up how eslisp solves this and it does

```
"(" + input + "\n)"
```

which is cute, but now all the offsets are off by one!

**Comment by anko** [comment]
This is a historical artefact from fwg/s-expression#5 being rejected.
(s-expr-plus is a fork of [fwg/s-expression](https://github.com/fwg/s-expression).)

I agree with you. S-expressions are usually used for code, where it's implicit that multiple of them might be present, so returning an array would make sense.

**Comment by anko** [comment]
In v7.0.0.

I'll update eslisp to use it soon, to fix the offset thing hackiness you point out.
